"""
Central configuration for the Stock Market Index Movement Forecasting project.

Keeping every tunable value in one place makes the rest of the codebase
easier to read and avoids "magic numbers" scattered across modules.
All paths are built with pathlib so the project works unchanged after
being moved to a different computer / drive letter.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict

# --------------------------------------------------------------------------
# Base paths
# --------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
SAMPLE_DATA_DIR = DATA_DIR / "sample"

MODELS_DIR = BASE_DIR / "models"
TRAINED_MODELS_DIR = MODELS_DIR / "trained"
SCALERS_DIR = MODELS_DIR / "scalers"
METADATA_DIR = MODELS_DIR / "metadata"

for _dir in (
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    SAMPLE_DATA_DIR,
    TRAINED_MODELS_DIR,
    SCALERS_DIR,
    METADATA_DIR,
):
    _dir.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------------------------------
# Supported market indices
# --------------------------------------------------------------------------
# Keys are short, filesystem-safe identifiers used for model/scaler filenames.
INDEX_OPTIONS: Dict[str, Dict[str, str]] = {
    "NIFTY50": {
        "label": "NIFTY 50",
        "yf_ticker": "^NSEI",
        "currency_label": "index points",
        "sample_csv": "NIFTY50_sample.csv",
    },
    "SENSEX": {
        "label": "S&P BSE SENSEX",
        "yf_ticker": "^BSESN",
        "currency_label": "index points",
        "sample_csv": "SENSEX_sample.csv",
    },
}

DEFAULT_INDEX_KEY = "NIFTY50"

# --------------------------------------------------------------------------
# Data download defaults
# --------------------------------------------------------------------------
DEFAULT_HISTORY_YEARS = 7          # ~last 7 years of daily data by default
MIN_REQUIRED_ROWS = 250            # minimum rows needed for a meaningful model

REQUIRED_OHLCV_COLUMNS = ["Open", "High", "Low", "Close", "Volume"]

# --------------------------------------------------------------------------
# Technical indicator parameters
# --------------------------------------------------------------------------
SMA_WINDOWS = [20, 50]
EMA_WINDOWS = [12, 26]

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

# --------------------------------------------------------------------------
# Feature set used to train the model
# --------------------------------------------------------------------------
FEATURE_COLUMNS = [
    "Open",
    "High",
    "Low",
    "Close",
    "Volume",
    "SMA_20",
    "SMA_50",
    "EMA_12",
    "EMA_26",
    "MACD",
    "MACD_SIGNAL",
    "MACD_HIST",
    "RSI_14",
]

TARGET_COLUMN = "Close"

# --------------------------------------------------------------------------
# Chronological train / validation / test split
# --------------------------------------------------------------------------
TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15  # kept for readability; derived as 1 - TRAIN_RATIO - VAL_RATIO

# --------------------------------------------------------------------------
# Sequence / LSTM defaults
# --------------------------------------------------------------------------
DEFAULT_LOOKBACK = 60          # trading days used as one input sequence
DEFAULT_EPOCHS = 20
DEFAULT_BATCH_SIZE = 32
DEFAULT_LSTM_UNITS_1 = 64
DEFAULT_LSTM_UNITS_2 = 32
DEFAULT_DROPOUT = 0.2
DEFAULT_DENSE_UNITS = 16
DEFAULT_LEARNING_RATE = 1e-3

# Direction classification threshold (fraction of latest close).
# A predicted move smaller than this is labeled NEUTRAL instead of UP/DOWN.
DIRECTION_NEUTRAL_THRESHOLD = 0.0005  # 0.05%

# --------------------------------------------------------------------------
# Multi-day experimental forecast
# --------------------------------------------------------------------------
MULTI_DAY_HORIZONS = [1, 3, 5]

# --------------------------------------------------------------------------
# Disclaimers (shown verbatim in the UI)
# --------------------------------------------------------------------------
EDUCATIONAL_DISCLAIMER = (
    "Predictions generated by this system are for educational and research "
    "purposes only and should not be considered financial or investment advice."
)

MULTI_STEP_DISCLAIMER = (
    "Experimental multi-step forecast — uncertainty increases as the forecast "
    "horizon grows. This is not a guaranteed future price."
)

SAMPLE_DATA_NOTICE = "Using bundled sample dataset."


def get_index_options_labels() -> Dict[str, str]:
    """Return a mapping of index key -> human readable label for UI selectboxes."""
    return {key: value["label"] for key, value in INDEX_OPTIONS.items()}


def model_paths(index_key: str) -> Dict[str, Path]:
    """Return the standard ticker-specific file paths for a saved model bundle."""
    return {
        "model": TRAINED_MODELS_DIR / f"{index_key}_lstm.keras",
        "scaler": SCALERS_DIR / f"{index_key}_scaler.pkl",
        "metadata": METADATA_DIR / f"{index_key}_metadata.json",
    }
